### ISSUE TITLE
Runner user is not allowed to use docker

### ISSUE THREAD

**Issue by SystemKeeper** [whywaita/actions-runner-images-lxd#23]
Thank you for your work to make the actions runner images available on LXD!

I noticed that on GitHub the user `runner` is allowed to use docker, while on LXD the is user is not allowed to do so. So currently we manually add the `runner` user to the `docker` group:
```
usermod -a -G docker runner
```

Maybe it makes sense to add that to your patch by default.

**Comment by whywaita** [comment]
@SystemKeeper Thanks, I fixed in #24

**Comment by SystemKeeper** [comment]
Perfect, thank you!
